### ISSUE TITLE
root password?

### ISSUE THREAD

**Issue by yashamon** [nmilosev/crouton-fedora-wayland#10]
So I enter wayland, open a terminal try to install something and it asks for a root passwd. 
What is this? I am guessing that given this we can install and run Gnome from wayland terminal, is there a a way to enter Gnome directly from chrome shell?

**Comment by nmilosev** [comment]
Root password should be unset or ```fedora```. Try that.

As for gnome, I'm unaware of any straight forward method. Possibly running gnome-session somehow?

**Comment by davidthewatson** [comment]
fedora worked for me. Thanks!

**Comment by nmilosev** [comment]
No problem, glad you solved it! :)
