### ISSUE TITLE
Install no longer works because of wget

### ISSUE THREAD

**Issue by ustomerus** [nmilosev/crouton-fedora-wayland#16]
Wget was removed from chrome OS in version 64, breaking the installer. 

> Installing fedora-x86_64 chroot to /usr/local/crouton-fedora/chroots/fedora
>
>Getting Docker build from Fedora official repositories...
>
>./crouton-fedora-wayland-master/installer/main.sh: 16: ./crouton-fedora-wayland-master/installer/../installer/fedora/bootstrap: wget: not found

**Comment by ghost** [comment]
try https://github.com/skycocker/chromebrew you can then run
`crew install wget`

**Comment by boydkelly** [comment]
For F30 it now works again....  with curl instead of wget.
