### ISSUE TITLE
Does Wayland enable GPU Acceleration in windowed chroot?

### ISSUE THREAD

**Issue by zguithues** [nmilosev/crouton-fedora-wayland#8]
I've poked around and didn't see anyone address this possibility...

Currently, on the main crouton, you either get:
GPU Acceleration fullscreen with xorg
or
NO GPU Acceleration in a window (or fullscreen) with xiwi.

Does the replacement of x with wayland enable GPU Acceleration in a window?

@nmilosev

**Comment by nmilosev** [comment]
> Currently, on the main crouton, you either get:
GPU Acceleration fullscreen with xorg
or
NO GPU Acceleration in a window (or fullscreen) with xiwi.

Absolutely correct, sadly if you need GPU acceleration you have to use the "old" X method. Sorry!

**Comment by zguithues** [comment]
BOOO!!!

I thought that was probably the case, but i wanted to be sure.

Thanks for clearing it up for me!
