### ISSUE TITLE
failed to run command '/prepare.sh' : Exec format error

### ISSUE THREAD

**Issue by kewp** [nmilosev/crouton-fedora-wayland#9]
Running on an old Chromebook HP 11 (recently updated).

It happened right after "Installing crash_reporter_wrapper into the host..."

Not sure what other information to provide.

**Comment by kewp** [comment]
It looks like it's downloading the test/26_Alpha/Docker/x86_64 image. Shouldn't this be armhfp ? I've tried forcing it using -a armhfp but it still downloads the 64 bit one.

**Comment by nmilosev** [comment]
Hello, 

Sadly I never tested this on ARM. You should try editing here: https://github.com/nmilosev/crouton-fedora-wayland/blob/master/installer/fedora/defaults

It seems I hard-coded it, sorry!

**Comment by nmilosev** [comment]
Please try again now!

**Comment by kewp** [comment]
It got past the previous point and started installing sudo. It died but I think my internet dropped out. Trying again.

**Comment by kewp** [comment]
Works great.
